import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/lib_front/store";
import { AuthProvider } from "@/lib_front/AuthContext";
import { NotificationToast } from "@/components/ui/NotificationToast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  variable: "--font-press-start",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased bg-black min-h-screen" suppressHydrationWarning>
        <AuthProvider>
          <AppProvider>
            {children}
            <NotificationToast />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}