services:
  # Service Backend Fastify
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendance-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/database.sqlite
    volumes:
      - ./backend/src:/app/src
      - ./database:/app/data
      - /app/node_modules
    networks:
      - transcendance-network
    restart: unless-stopped
    
  # Service Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Utiliser un Dockerfile de développement
    container_name: transcendance-frontend
    ports:
      - "8080:8080"  # Next.js dev server port
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - transcendance-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  transcendance-network:
    driver: bridge